"use strict";
Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
const superEditor_es = require("./chunks/super-editor.es-BB3EzkkR.cjs");
require("./chunks/vue-CenuKwdP.cjs");
exports.AIWriter = superEditor_es.AIWriter;
exports.AnnotatorHelpers = superEditor_es.AnnotatorHelpers;
exports.BasicUpload = superEditor_es._sfc_main;
exports.CommentsPluginKey = superEditor_es.CommentsPluginKey;
exports.DocxZipper = superEditor_es.DocxZipper;
exports.Editor = superEditor_es.Editor;
exports.Extensions = superEditor_es.Extensions;
exports.SectionHelpers = superEditor_es.SectionHelpers;
exports.SlashMenu = superEditor_es._sfc_main$4;
exports.SuperConverter = superEditor_es.SuperConverter;
exports.SuperEditor = superEditor_es.SuperEditor;
exports.SuperInput = superEditor_es.SuperInput;
exports.SuperToolbar = superEditor_es.SuperToolbar;
exports.Toolbar = superEditor_es.Toolbar;
exports.TrackChangesBasePluginKey = superEditor_es.TrackChangesBasePluginKey;
exports.createZip = superEditor_es.createZip;
exports.fieldAnnotationHelpers = superEditor_es.index$1;
exports.getActiveFormatting = superEditor_es.getActiveFormatting;
exports.getAllowedImageDimensions = superEditor_es.getAllowedImageDimensions;
exports.getMarksFromSelection = superEditor_es.getMarksFromSelection;
exports.getRichTextExtensions = superEditor_es.getRichTextExtensions;
exports.getStarterExtensions = superEditor_es.getStarterExtensions;
exports.helpers = superEditor_es.helpers;
exports.trackChangesHelpers = superEditor_es.index;
